version: '3'

includes:
  docker:
    taskfile: ./buildrun/docker/docker-compose/dev-env/Taskfile.yml
    dir: ./buildrun/docker/docker-compose/dev-env/

tasks:
  install-precommit:
    - brew install pre-commit
    - pre-commit install
  install-black:
    - pip install black
  install-dependencies:
    desc: install needed dependencies for this project
    cmds:
      - task: install-precommit
      - task: install-black
