# Generated by Django 4.1.3 on 2022-12-04 18:20

from django.conf import settings
from django.db import migrations


def set_site_name(apps, name, domain):
    Site = apps.get_model("sites", "Site")
    Site.objects.update_or_create(
        pk=settings.SITE_ID, defaults={"name": name, "domain": domain}
    )


def set_personnalised_site_name(apps, schema_editor):
    set_site_name(apps, settings.SITE_NAME, settings.SITE_DOMAIN)


class Migration(migrations.Migration):
    dependencies = [
        ("common", "0001_initial"),
        ("sites", "0002_alter_domain_unique"),
    ]

    operations = [
        migrations.RunPython(set_personnalised_site_name, migrations.RunPython.noop),
    ]
